frr version 8
frr defaults traditional
hostname moouahab-router
service integrated-vtysh-config

!
router bgp 65000
 bgp router-id 1.1.1.1
!
router ospf
 ospf router-id 1.1.1.1
!
router isis MOOUAHAB
 net 49.0001.0000.0000.0001.00
 is-type level-2-only
!
line vty
!
